language: java

dist: xenial

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: skip
script:
  - mvn -f Goobi/pom.xml clean install -Dmaven.javadoc.skip=true -B -V

notifications:
  slack:
    secure: hcBY6yKkEAP7QF6XuBdVlfHbERg5LRT6EuiDXzfAzdMBvIoB0yhTYouyDE7UdHFua19RfeA5ZaYfwSYIPlUUU7mBUS6lp9F7B9EqM0x2y5BCXT7HCU4jdeqt7qT+p6ykoViHOODnHCJCv4S09dga6nVl5Br/NjdIHP8MZmuUj632kTorJqJb6xrxQoNjOYOcLEMF7iTWPLbzBvop0Lm2hlpS+Q6KocGFkIySvTcgTuctJevxaY4qH3cCKYCnbqusLKPLTwIroJitgyUzbxy8sQQdKaOxBMWhNbsacn7fkFf8JgZw2p57qmbLGB8GEYNsx2c0fuFHr76OaASa718yHi9ID7qm4YAXgoxzPL6H6S56L5lQ1GvPK9iWfHlF45uVNDPj2BekA8G0TA+eyrNpLwL2LGxAwcpdOjtdo8ZRSFfw4eU62H9leeHxtpa/XYf/QT6JWkPN+4X/yePILfBc5zqPBeAw2oT/NciX2a3L8xFCLlJCZ9gH363RKFgHC59wiR3MLLGw/0KxG2QEAiAZVUxipI4Qo3hFHa8K7mSLRMSozKDu5o1c9CLp6y9d3o56bQsrVndPCMBjIH2M5YMYFIeWNQ0hVp3c1mbVykXfRMhVr7Gv8EIXfWanYUyvmq5HbT5xyE8/o8Z2FV9n9hl7LRJ9c2pjVXf9OquSpdJbIEw=

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SxGx/knSvgW2pfU3DEVI0lcplLblWy5YgDB1qMBmmuTR3P3PhWXSVga9+TyqBpIYAQoU+CcYzVvtcvJZ/fqZzzUjdKzBG02q+m74XN8h+lzGYsJhS4OM72adWI731K9adItbAX9Z8/a8JG9/5iFCNwQ2aGUGv1oUnB5F6v9jkrCUx/HB7qR6fh/waJnz7q2gRn0leOT9CVZVFyw4i0jeRuzjRBh30kPzOw5zTq3Kzx9p9f4V36XNyfIjwr0JjXUgYXo28ytqUFRf4+CnVkJ2JjZrOuxAhz4uuQoagsdh0O6nZEsTBJXo/jDjwP+j6sqHYDwTBS0Jp1WzNO6lv5n4v5Czxas+9e1/4l5qL8fiT6BmOAbVb6dnOMNclTyxXKi8GnsQRLGFl2vy60bCsct929GUKuRgdnd7rrYx2pDL53lO1sj7wzsR9po0VmWYVw1KT+KcSQkAgg20Ux3qY9TLEvId6lbCM2FSZPVLVdNCD68nhWGERGK+QGyPWu0Ka79O7S9oWq0NIZUvOyS2fM1lWCeNQOOjzU8Hgi0X1mSx/blEx9XrTkJDZmOKpeBq8SSKSMay3jDCZe9s5U37OWKk9KqUqLT8u5mTa80JFFt697sKiN6vDA+5DO9k7VBl4hYRk0RvcpJsYfVkxp896vYJ6+JRDMFVaYhEbwZNbhUWhYo=
  file: Goobi/module-war/target/goobi.war
  on:
    repo: intranda/goobi
    tags: true
    condition: $TRAVIS_TAG =~ ^v